# Generated by Django 4.2.4 on 2023-08-21 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_title', models.CharField(max_length=200, verbose_name='Заметка')),
                ('note_text', models.TextField(verbose_name='Что сделать')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('do_before', models.DateTimeField(verbose_name='Сделать до')),
                ('pub_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
