# Generated by Django 4.2.4 on 2023-08-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='do_before',
            field=models.DateField(blank=True, verbose_name='Сделать до'),
        ),
    ]
