# Generated by Django 4.2.4 on 2023-08-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_do_before'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': [('NoteOwner', 'Can see notes')]},
        ),
    ]
