# Generated by Django 4.2.4 on 2023-08-21 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_alter_note_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernote', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
