# Generated by Django 4.2.4 on 2023-09-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_pub_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Сделано'),
        ),
    ]
